### ISSUE TITLE
pretrained model

### ISSUE THREAD

**Issue by Abhijit-2592** [sanjay235/Sketch2Color-anime-translation#2]
Hi can you provide a pre trained model?

**Comment by mwmw7** [comment]
Hello this is really good repository 
But I am struggling when I set it up and download data

**Comment by sanjay035** [comment]
I've used Google colab for the training process. It's worked well for me.

**Comment by sanjay035** [comment]
> Hi can you provide a pre trained model?
Hi, I've added them to the pre-trained models folder. Please check.

**Comment by sanjay235** [comment]
> > Hi can you provide a pre trained model?
> > Hi, I've added them to the pre-trained models folder. Please check.

**Comment by Abhijit-2592** [comment]
@sanjay235 Cool thanks. But I was able to train your code and get the weights. It worked great. Thanks for the awesome tutorial!
